version: "3"
services:
  container1:
    image: whujin11e/public:azure_voting_app
    container_name: app
    networks:
      backend:
    depends_on:
      - "database"
    environment:
      - DB_PASSWORD="BLA"
    ports:
      - 8080:80
    
  
  database:
    image: redis:latest
    container_name: database
    networks:
      backend:
    volumes:
      - ./storage/database

networks:
  backend:
    external: false
