version: "3"
services:
  container1:
    image: docker pull redis:latest
    container_name: database
    networks:
      backend:
    volumes:
      - ./storage/database
  
  container2:
    image: whujin11e/public:azure_voting_app
    container_name: app
    networks:
      backend:
    depends_on:
      - "database"
    environment:
      - DB_PASSWORD="BLA"
    ports:
      - 8080:80

networks:
  backend:
    external: false
